# Generated by Django 4.2.1 on 2024-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_studentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='useranswer',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
